#!/bin/sh

# Tests that require a real svn repository and executable.

. ./common.sh

check_svn()
{
    check_available \
        "svn --version" \
        "svn, version " \
        "svn not found: skipping this test script"
    need=`svn --version | head -n1 | sed 's/, version /-/; s/\.[0-9]* .*//'`
    check_feature $need "$need not built in: skipping this test script"
}

find_svnrepo()
{
    svnrepo="$testdir/svn-repo.tar"
    if [ ! -f $svnrepo ]; then
        echo "$svnrepo not found" >&2
        exit 1
    fi
}

pretest()
{
    checkout_path=$1
    [ -d $tmpdir ] || die "tmpdir ($tmpdir) does not exist"
    cd $tmpdir
    rm -rf svn-repo svn-wc
    tar -xf $svnrepo
    repourl=file://$tmpdir/svn-repo
    svn -q checkout $repourl/$checkout_path svn-wc
    cd svn-wc
}

posttest()
{
    cd $tmpdir
    rm -rf svn-repo svn-wc
}

# default prompt format in test repo
test_basics()
{
    echo "test_basics:"
    pretest "trunk"
    assert_vcprompt "vc name" "svn" "%n"
    assert_vcprompt "branch name on trunk" "trunk" "%b"
    assert_vcprompt "rev num on trunk" "2" "%r"

    svn -q switch $repourl/branches/stable
    assert_vcprompt "branch name on non-trunk branch" "stable" "%b"
    assert_vcprompt "rev num on branch" "4" "%r"

    # XXX checkout whole project: /trunk + /branches + /tags
    # XXX in a subdir: /trunk/d, /branches/stable/d

    posttest
}

test_weird_checkout()
{
    # checkout the whole repo, ie. parent of trunk/, tags/, branches/
    echo "test_weird_checkout:"
    pretest ""
    assert_vcprompt "vc name" "svn" "%n"
    assert_vcprompt "no branch name (in project root)" "" "%b"

    cd trunk
    assert_vcprompt "branch name on trunk" "trunk" "%b"

    cd ../branches/stable
    assert_vcprompt "branch name on non-trunk branch" "stable" "%b"


    posttest
}

find_vcprompt
check_svn
find_svnrepo
setup

test_basics
test_weird_checkout
